### ISSUE TITLE
Remove Page Numbers from Text

### ISSUE THREAD

**Issue by jschulberg** [vikrapivin/congressional-record-analysis#3]
These appear in one of two formats:

1. [[H####]]
2. [[S####]]

**Comment by jschulberg** [comment]
[[Page S838]]

**Comment by jschulberg** [comment]
@vikrapivin think I got it! I created some regex to remove both the page numbers and the general header in each string of text:

[https://github.com/vikrapivin/congressional-record-analysis/blob/main/2.%20Text%20Analysis/continue_parsing.py#L27-L63](https://github.com/vikrapivin/congressional-record-analysis/blob/main/2.%20Text%20Analysis/continue_parsing.py#L27-L63)

**Comment by vikrapivin** [comment]
@jschulberg that looks good. I tweaked it a bit. Let  me know if the comments I made are useful and easy to understand. I will add this to the parsing script later.
